api_platform:
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    http_cache:
        public: true
    defaults:
        pagination_enabled: false
        cache_headers:
            max_age: 86400
            vary: [ 'Content-Type', 'Origin', 'Access-Control-Allow-Origin' ]
            etag: false
