version: "3.8"

services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony_app

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony_app

  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/initial_data:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - symfony_app

networks:
  symfony_app: